version: 2
jobs:
  build:
    working_directory: ~/circleci-genex
    docker:
      - image: circleci/python:3.7.3 # primary container for the build job
    steps:
      - checkout # checkout source code to working directory
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install .
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - "env"
      - run:
          command: |
            . env/bin/activate
        
